### ISSUE TITLE
Should vega-loader send cookies when loading data?

### ISSUE THREAD

**Issue by sid-kap** [vega/vega-loader#10]
Hi,

I've run into an issue in JupyterLab where loading the dataset doesn't work if JupyterLab is running in password-protected mode. This is because vega-loader doesn't use cookies when using `fetch` to load the data.

I was able to work around this issue by including `credentials: 'same-origin'` in the loader options (I've opened a PR with this change at https://github.com/jupyterlab/jupyterlab/pull/4707), but someone suggested that this change might be worth upstreaming directly to vega-loader.

Do you think this would be a good idea?

**Comment by jheer** [comment]
We use the standard fetch behavior, which is safer (albeit in some cases less convenient) by default. If cookies are needed, please use the loader options. I would recommend adding them to JupyterLab (or ipyvega, or similar) as you've suggested! Even if we ultimately make the change here, it is probably good for environments embedding Vega to explicitly set and maintain their own policies.

**Comment by josemarfdc** [comment]
@sid-kap how exactly you would include `credentials: 'same-origin'` in the loader options?

**Comment by domoritz** [comment]
Would it make sense to change the default in Vega-Embed (which would propagate to JupyterLab and ipyvega)?

**Comment by sid-kap** [comment]
@jheer, thanks for your response! That makes sense. I guess I can close this issue then.

@josemarfdc I've done this by adding `http: { credentials: 'same-origin' }` to the loader options. See the PR I linked above.

**Comment by jheer** [comment]
@domoritz I think changing this setting in vega-embed is a reasonable action if the consensus is that same-origin cookies should be used by default. This change is probably the most consequential difference between Fetch and XMLHttpRequest.

**Comment by domoritz** [comment]
I decided not to change the default here as it is safer not to send credentials around. Instead, I made it super easy to change loader options by passing an object instead of a loader to embed. Embed will then create a loader for you. 

I also added a note to the readme: https://github.com/vega/vega-embed#how-do-i-send-cookies-when-loading-data
